### ISSUE TITLE
locality: more character encoding issues

### ISSUE THREAD

**Issue by missinglink** [pelias/quattroshapes-patch#10]
http://pelias.mapzen.com/doc?id=osmnode:3485575196

``` bash
"locality": "ÎÎÎÎÎÎ"
```

**Comment by missinglink** [comment]
http://pelias.mapzen.com/doc?id=osmway:228966671

``` javascript
locality: "DzierÅ¼oniÃ³w",
```

**Comment by missinglink** [comment]
further issues noted in https://github.com/pelias/api/issues/224

**Comment by orangejulius** [comment]
All fixed!

http://pelias.github.io/compare/#/v1/place%3Fids=openstreetmap:venue:node:3485575196
http://pelias.github.io/compare/#/v1/place%3Fids=openstreetmap:venue:way:228966671
