### ISSUE TITLE
Compute admin0, admin1, admin2 popularity scores

### ISSUE THREAD

**Issue by hkrishna** [pelias/quattroshapes-patch#4]
As we know ```localadmin``` ```localities``` and ```neighborhoods``` have popularity ratings. We should look into using this information and saving it to ```admin0```, ```admin1``` and ```admin2``` so that a point in a popular state is scored higher even though it doesnt intersect in a popular neighborhood. 

This [issue](https://github.com/pelias/admin-lookup/issues/5) deals with adding using popularity information while we perform admin lookup for each geospatial point with a lat/lon. With this patch we would be able to perform the same thing for all the points!

**Comment by sevko** [comment]
I'll begin by assigning popularity values for `adm0` through `localities` polygons based on the `neighborhood` polys that they contain (which is the only layer that contains popularity), probably just summing them up.

**Comment by hkrishna** [comment]
Summing them up sounds good. Lets not do anything too complicated at this stage.

**Comment by sevko** [comment]
Landed in #5 .
